apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-vgxm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-vgxm
    app.kubernetes.io/part-of: apicurio-registry
  name: apicurio-registry-vgxm
  namespace: burrsitis-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: apicurio-registry-vgxm
status:
  loadBalancer: {}
